# Generated by Django 3.2 on 2023-03-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='First', max_length=15)),
                ('email', models.EmailField(default='Email', max_length=50)),
                ('contact', models.CharField(default='0123456789', max_length=10)),
                ('password', models.CharField(default='Passwd', max_length=250)),
                ('role', models.CharField(default='applicant', max_length=20)),
                ('location', models.CharField(default='applicant', max_length=20)),
                ('gender', models.CharField(default='applicant', max_length=20)),
                ('totalPoints', models.IntegerField(default='50')),
                ('date_of_creation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=20)),
                ('email', models.EmailField(default='email', max_length=50)),
                ('password', models.CharField(default='passwd', max_length=250)),
                ('role', models.CharField(default='company', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('date_of_creation', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
