# Generated by Django 3.2 on 2023-03-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliedOn', models.DateTimeField(auto_now=True)),
                ('isSelected', models.BooleanField(default=False)),
                ('bidPoints', models.CharField(default='nan', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jobapplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='company', max_length=20)),
                ('description', models.CharField(default='description', max_length=20)),
                ('location', models.CharField(default='location', max_length=20)),
                ('Jobtype', models.CharField(default='nan', max_length=20)),
                ('startDate', models.CharField(default='nan', max_length=20)),
                ('duration', models.CharField(default='nan', max_length=10)),
                ('stipend', models.CharField(default='00', max_length=10)),
                ('skillsRequired', models.CharField(default='skills', max_length=250)),
                ('whoCanApply', models.CharField(default='apply', max_length=250)),
                ('totalOpenings', models.CharField(default='nan', max_length=10)),
                ('availableOpenings', models.CharField(default='nan', max_length=10)),
                ('isInternship', models.BooleanField(default=False)),
                ('jobUploadedOn', models.DateTimeField(auto_now=True)),
                ('companyId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='xyz', max_length=45)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Description', models.TextField(default='NA')),
                ('Status', models.CharField(default='NA', max_length=20)),
                ('Comments', models.TextField(default='NA')),
                ('Usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=False)),
                ('applicationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.application')),
                ('jobId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobapplication')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.applicant')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='jobId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobapplication'),
        ),
        migrations.AddField(
            model_name='application',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.applicant'),
        ),
    ]
