# Generated by Django 3.2 on 2023-03-10 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230310_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='Jobtype',
        ),
        migrations.AddField(
            model_name='applicant',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='applicationViewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievance',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.company'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobType',
            field=models.CharField(default='Remote', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='appliedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 22, 54, 32, 685773)),
        ),
        migrations.AlterField(
            model_name='application',
            name='bidPoints',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='chat',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 22, 54, 32, 685773)),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='Comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='Name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='Status',
            field=models.CharField(default='Grievance Filled', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='availableOpenings',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jobUploadedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 10, 22, 54, 32, 685773)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='skillsRequired',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 22, 54, 32, 685773)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='stipend',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='totalOpenings',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='whoCanApply',
            field=models.TextField(default=''),
        ),
    ]
