# Generated by Django 3.2 on 2023-03-11 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230310_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='chatExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='appliedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 7, 3, 16, 332507)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 7, 3, 16, 332507)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 7, 3, 16, 332507)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jobUploadedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 7, 3, 16, 332507)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 7, 3, 16, 332507)),
        ),
    ]
