# Generated by Django 3.2 on 2023-03-11 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230311_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appliedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 10, 43, 29, 163645)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 10, 43, 29, 163645)),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 10, 43, 29, 163645)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='jobUploadedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 10, 43, 29, 163645)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 10, 43, 29, 163645)),
        ),
    ]
